### Login
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
    "username": "mohammad",
    "password": "123456"
}

###

### Register
POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
    "username": "ali",
    "password": "1234",
    "firstName": "Ali",
    "lastName": "Ahmadi",
    "phone": "09123456789",
    "email": "ali@test.com"
}

###

### Register
POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
    "username": "mohammad",
    "password": "123456",
    "firstName": "Mohammad",
    "lastName": "Vahed",
    "phone": "09120000000",
    "email": "mohammad@test.com"
}

###

### Token
GET http://localhost:8080/api/test
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhbGkiLCJpYXQiOjE3ODQ1Nzk5OTAsImV4cCI6MTc4NDY2NjM5MH0.kDrSoKXhdbfijUUqpkCkIR783U4T3xd-75fr_U4JI5U

###

### Advertisement create
POST http://localhost:8080/api/advertisements
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJtb2hhbW1hZCIsImlhdCI6MTc4NDY4MDk4MiwiZXhwIjoxNzg0NzY3MzgyfQ.Ydz2NiVd4hqDL0SDteIlyRMuM0sTDV9F3WqmcfrFFT0
Content-Type: application/json

{
  "title":"isPhone 13",
  "description":"fsd",
  "price":35000000,
  "city":"Tehran",
  "category":"DIGITAL"
}

###

### Advertisement all
GET http://localhost:8080/api/advertisements

###

### User Advertisement
GET http://localhost:8080/api/advertisements/my
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJtb2hhbW1hZCIsImlhdCI6MTc4NDY4MDk4MiwiZXhwIjoxNzg0NzY3MzgyfQ.Ydz2NiVd4hqDL0SDteIlyRMuM0sTDV9F3WqmcfrFFT0

###

### User Advertisement
PUT http://localhost:8080/api/advertisements/1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJtb2hhbW1hZCIsImlhdCI6MTc4NDY4MDk4MiwiZXhwIjoxNzg0NzY3MzgyfQ.Ydz2NiVd4hqDL0SDteIlyRMuM0sTDV9F3WqmcfrFFT0
Content-Type: application/json

{
  "title":"fdkfl 13",
  "description":"128G",
  "price":45000000
}

###

### User Advertisement
GET http://localhost:8080/api/admin/advertisements/pending
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJtb2hhbW1hZCIsImlhdCI6MTc4NDc1ODczMywiZXhwIjoxNzg0ODQ1MTMzfQ.HtvHPYMuBny-wrZgrs1Nj_KXyhOz13-_Ry4xiy46sBY