### Login
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
    "username": "ali",
    "password": "1234"
}

###

### Register
POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
    "username": "ali",
    "password": "1234",
    "firstName": "Ali",
    "lastName": "Ahmadi",
    "phone": "09123456789",
    "email": "ali@test.com"
}

###

### Register
POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
    "username": "mohammad",
    "password": "123456",
    "firstName": "Mohammad",
    "lastName": "Vahed",
    "phone": "09120000000",
    "email": "mohammad@test.com"
}

###

### Token
GET http://localhost:8080/api/test
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhbGkiLCJpYXQiOjE3ODQ1Nzk5OTAsImV4cCI6MTc4NDY2NjM5MH0.kDrSoKXhdbfijUUqpkCkIR783U4T3xd-75fr_U4JI5U

###

### Advertisement create
POST http://localhost:8080/api/advertisements
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhbGkiLCJpYXQiOjE3ODQ1Nzk5OTAsImV4cCI6MTc4NDY2NjM5MH0.kDrSoKXhdbfijUUqpkCkIR783U4T3xd-75fr_U4JI5U
Content-Type: application/json

{
  "title":"isPhone 13",
  "description":"fsd",
  "price":35000000,
  "city":"Tehran"
}

###

### Advertisement all
GET http://localhost:8080/api/advertisements